import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fefefe',
  },
  loadingContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 18,
    color: '#666',
    fontStyle: 'italic',
  },
  verticalPager: {
    flex: 1,
    width: screenWidth,
    height: screenHeight,
  },
  verticalPage: {
    width: screenWidth,
    height: screenHeight,
    justifyContent: 'center',
  },
  poemContainer: {
    flex: 1,
    paddingHorizontal: 35,
    paddingVertical: 60,
  },
  saveButton: {
    position: 'absolute',
    top: 54,
    right: 28,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderWidth: 1,
    borderColor: '#e8e2d8',
    zIndex: 2,
  },
  libraryButton: {
    position: 'absolute',
    top: 54,
    left: 28,
    minWidth: 72,
    height: 40,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.82)',
    borderWidth: 1,
    borderColor: '#e8e2d8',
    zIndex: 2,
  },
  libraryButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#5f5a52',
  },
  saveButtonActive: {
    backgroundColor: '#2c2c2c',
    borderColor: '#2c2c2c',
  },
  saveButtonPressed: {
    opacity: 0.72,
  },
  saveButtonIcon: {
    fontSize: 22,
    lineHeight: 24,
    color: '#6f6a61',
  },
  saveButtonIconActive: {
    color: '#ffffff',
  },
  pager: {
    flex: 1,
  },
  pagerPage: {
    flex: 1,
  },
  poemPage: {
    flex: 1,
    justifyContent: 'space-between',
  },
  poemHeader: {
    marginBottom: 40,
    alignItems: 'center',
    paddingHorizontal: 54,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: '#2c2c2c',
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: 'serif',
  },
  author: {
    fontSize: 16,
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'center',
  },
  poemBody: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  stanza: {
    marginBottom: 24,
    width: '100%',
  },
  line: {
    fontSize: 18,
    lineHeight: 28,
    color: '#333',
    marginBottom: 2,
    fontFamily: 'serif',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ddd',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: '#666',
  },
  titleUrdu: {
    fontSize: 24,
    fontWeight: '600',
    color: '#2c2c2c',
    textAlign: 'right',
    marginBottom: 8,
    fontFamily: 'NotoNastaliqUrdu_400Regular',
    writingDirection: 'rtl',
  },
  authorUrdu: {
    fontSize: 16,
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'right',
    fontFamily: 'NotoNastaliqUrdu_400Regular',
    writingDirection: 'rtl',
  },
  lineUrdu: {
    fontSize: 18,
    lineHeight: 28,
    color: '#333',
    marginBottom: 2,
    textAlign: 'right',
    fontFamily: 'NotoNastaliqUrdu_400Regular',
    writingDirection: 'rtl',
  },
  libraryContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#fefefe',
    zIndex: 5,
  },
  libraryContent: {
    flex: 1,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    paddingTop: 58,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  libraryHeader: {
    gap: 4,
    marginBottom: 22,
  },
  libraryHeaderTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
  },
  libraryTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
  },
  librarySubtitle: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
    color: '#7a746b',
  },
  libraryHeaderButton: {
    minWidth: 64,
    minHeight: 40,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e8e2d8',
    backgroundColor: '#ffffff',
  },
  libraryHeaderButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5f5a52',
  },
  libraryHeaderActions: {
    flexDirection: 'row',
    gap: 8,
  },
  librarySegmentedControl: {
    minHeight: 46,
    flexDirection: 'row',
    padding: 3,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#e8e2d8',
    backgroundColor: '#f7f4ef',
    marginBottom: 18,
  },
  librarySegment: {
    flex: 1,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    paddingHorizontal: 12,
  },
  librarySegmentActive: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ebe5dc',
  },
  librarySegmentText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#7a746b',
  },
  librarySegmentTextActive: {
    color: '#2c2c2c',
  },
  libraryListContent: {
    paddingBottom: 36,
    gap: 10,
  },
  libraryListHeader: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  librarySectionTitle: {
    flex: 1,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
  },
  librarySmallButton: {
    minWidth: 56,
    minHeight: 40,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e8e2d8',
    backgroundColor: '#ffffff',
  },
  librarySmallButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5f5a52',
  },
  libraryEmptyListContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 48,
  },
  libraryRow: {
    minHeight: 92,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee8df',
    backgroundColor: '#ffffff',
  },
  libraryRowPressed: {
    backgroundColor: '#f7f4ef',
  },
  libraryRowTitle: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
  },
  libraryRowAuthor: {
    marginTop: 3,
    fontSize: 14,
    lineHeight: 20,
    color: '#6f6a61',
    fontStyle: 'italic',
  },
  libraryRowPreview: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: '#5f5a52',
  },
  libraryEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  libraryEmptyTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
    textAlign: 'center',
  },
  libraryEmptyText: {
    maxWidth: 320,
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    color: '#7a746b',
    textAlign: 'center',
  },
  libraryDetailContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#fefefe',
    zIndex: 6,
  },
  libraryDetailHeader: {
    position: 'absolute',
    top: 54,
    left: 24,
    right: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 8,
  },
  libraryFormContent: {
    paddingBottom: 36,
  },
  libraryFormHeader: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  libraryFormTitleGroup: {
    flex: 1,
    gap: 3,
  },
  libraryFormSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: '#7a746b',
  },
  libraryFieldGroup: {
    marginBottom: 16,
  },
  libraryFieldLabel: {
    marginBottom: 6,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#5f5a52',
  },
  libraryTextInput: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e8e2d8',
    backgroundColor: '#ffffff',
    fontSize: 16,
    lineHeight: 22,
    color: '#2c2c2c',
  },
  libraryContentInput: {
    minHeight: 180,
    fontFamily: 'serif',
  },
  libraryFieldError: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 20,
    color: '#9f3428',
  },
  libraryPrimaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    borderRadius: 22,
    backgroundColor: '#2c2c2c',
  },
  libraryPrimaryButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#ffffff',
  },
  scannerContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#000000',
    zIndex: 20,
  },
  scannerCamera: {
    flex: 1,
  },
  scannerTopBar: {
    position: 'absolute',
    top: 54,
    left: 24,
    right: 24,
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  scannerOverlayButton: {
    minWidth: 76,
    minHeight: 44,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: 'rgba(25, 25, 25, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.28)',
  },
  scannerOverlayButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#ffffff',
  },
  scannerGuide: {
    position: 'absolute',
    top: 130,
    right: 28,
    bottom: 190,
    left: 28,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  scannerGuideFrame: {
    width: '100%',
    flex: 1,
    maxHeight: 560,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.78)',
    borderRadius: 14,
  },
  scannerGuideText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowRadius: 5,
  },
  scannerControls: {
    position: 'absolute',
    right: 24,
    bottom: 40,
    left: 24,
    gap: 14,
  },
  scannerControlRow: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  scannerControlSpacer: {
    width: 76,
  },
  scannerShutterOuter: {
    width: 76,
    height: 76,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 38,
    borderWidth: 4,
    borderColor: '#ffffff',
  },
  scannerShutterInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ffffff',
  },
  scannerErrorBanner: {
    alignSelf: 'center',
    overflow: 'hidden',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(116, 34, 28, 0.9)',
    fontSize: 14,
    lineHeight: 20,
    color: '#ffffff',
    textAlign: 'center',
  },
  scannerLoadingOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    backgroundColor: 'rgba(0, 0, 0, 0.68)',
  },
  scannerLoadingText: {
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '600',
    color: '#ffffff',
  },
  scannerPermissionContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    paddingHorizontal: 32,
    alignItems: 'stretch',
    justifyContent: 'center',
    gap: 14,
    backgroundColor: '#fefefe',
    zIndex: 20,
  },
  scannerPermissionTitle: {
    fontSize: 27,
    lineHeight: 34,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
    textAlign: 'center',
  },
  scannerPermissionText: {
    marginBottom: 8,
    fontSize: 15,
    lineHeight: 22,
    color: '#6f6a61',
    textAlign: 'center',
  },
  scannerError: {
    fontSize: 14,
    lineHeight: 20,
    color: '#9f3428',
    textAlign: 'center',
  },
  accountContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#fefefe',
    zIndex: 12,
  },
  accountContent: {
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
    paddingTop: 58,
    paddingHorizontal: 24,
    paddingBottom: 48,
    gap: 16,
  },
  accountHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 8,
  },
  accountTitle: {
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
  },
  accountSubtitle: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
    color: '#7a746b',
  },
  accountCard: {
    padding: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee8df',
    backgroundColor: '#ffffff',
    gap: 12,
  },
  accountSectionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '600',
    color: '#2c2c2c',
    fontFamily: 'serif',
  },
  accountBody: {
    fontSize: 15,
    lineHeight: 22,
    color: '#6f6a61',
  },
  accountEmail: {
    fontSize: 16,
    lineHeight: 22,
    color: '#2c2c2c',
  },
  accountStatus: {
    fontSize: 14,
    lineHeight: 20,
    color: '#52705a',
  },
  accountFieldLabel: {
    marginTop: 4,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    color: '#5f5a52',
  },
  accountAppleButton: {
    width: '100%',
    height: 44,
  },
  accountSecondaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#d9d2c8',
    backgroundColor: '#ffffff',
  },
  accountSecondaryButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2c2c2c',
  },
  accountDeleteButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#ddb9b4',
    backgroundColor: '#fff8f7',
  },
  accountDeleteButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#9f3428',
  },
  accountTextButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountTextButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5f5a52',
  },
  accountButtonDisabled: {
    opacity: 0.42,
  },
  accountError: {
    fontSize: 14,
    lineHeight: 20,
    color: '#9f3428',
    textAlign: 'center',
  },
});
